version: '3.8'

services:
  front:
    build:
      context: ../front
      dockerfile: ../docker/Dockerfile
    env_file: .env
    networks:
      - front-network
    volumes:
      - ../:/app
    ports:
      - 9992:9991
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    user: "${USER_ID}:${USER_GID}"

networks:
  front-network:
    driver: bridge
