version: '3.8'

services:
  front:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - front-network
    volumes:
      - ../:/app
    ports:
      - 9992:9991
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    # verify docker group ID, jenkins user will have same gid than your user on host (docker.sock perm)
    #user: "${USER_ID}:${DOCKER_GID}"

networks:
  front-network:
    driver: bridge
