version: '3.8'

services:
  jenkins:
    env_file: .env
    build: .
    ports:
      - "8081:8080"
    working_dir: /var/jenkins_home
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/raph/Documents/raph:/var/jenkins_home/raph
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    # verify docker group ID, jenkins user will have same gid than your user on host (docker.sock perm)
    user: "${USER_ID}:${DOCKER_GID}"

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
